# Generated by Django 5.2 on 2025-05-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
    ]
