# Generated by Django 5.2 on 2025-05-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
