# Generated by Django 5.2 on 2025-05-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'deliveries'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
