# Generated by Django 5.2 on 2025-05-08 05:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_remove_product_reviews_product_bonus_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manual',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
