# Generated by Django 5.2 on 2025-05-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_remove_product_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
        migrations.AddField(
            model_name='productimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products'),
        ),
    ]
