# Generated by Django 5.2 on 2025-05-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_remove_product_video_productimage_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='attribute_id',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_id',
            new_name='payment',
        ),
    ]
