# Generated by Django 5.2 on 2025-05-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_rename_attribute_id_product_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=1, upload_to='product/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
